[project]
name = "src"
version = "0.0.1"
description = "Project on Vehicle Insurance Domain"
authors = [{name="Saurav Sabu",email="saurav.sabu9@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}